version: '3'
services:
  server:
    container_name: peon.warcamp.vrising.${SERVERNAME}
    hostname: peon.steamcmd.vrising
    image: umlatt/steamcmd-winehq
    ports:
      - ${PORT}:${PORT}/udp
      - ${QUERYPORT}:${QUERYPORT}/udp
    environment:
      - STEAMID=1829350
      - PORT=${PORT}
      - QUERYPORT=${QUERYPORT}
      - SERVERNAME=${SERVERNAME}
      - WORLDNAME=${WORLDNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./data:/home/steam/steamcmd/data
      - ./server_start:/init/server_start
      - ./peon:/home/steam/config
      - ./user:/home/steam/peon_user_data