version: '3'
services:
  server:
    hostname: peon.steamcmd.vrising
    image: umlatt/steamcmd-winehq
    ports:
      - ${GAMEPORT}:${GAMEPORT}/udp
      - ${QUERYPORT}:${QUERYPORT}/udp
    environment:
      - STEAMID=1829350
      - GAMEPORT=${GAMEPORT}
      - QUERYPORT=${QUERYPORT}
    volumes:
      - ./data:/home/steam/steamcmd/data
      - ./server_start:/init/server_start
      - ./peon:/home/steam/peon
      # VRISING CUSTOM
      - ./init_custom:/init/init_custom
      #- ./user:/home/steam/.config/unity3d/IronGate/Valheim