version: '3'
services:
  server:
    hostname: peon.steamcmd.valhiem
    image: umlatt/steamcmd-winehq
    ports:
      - ${GAMEPORT}:${GAMEPORT}
      - ${QUERYPORT}:${QUERYPORT}
    environment:
      - STEAMID=1829350
      - GAMEPORT=${GAMEPORT}
      - QUERYPORT=${QUERYPORT}
    volumes:
      - ./server_files:/home/steam/server_files
      - ./server_start:/init/server_start
      # ONLY REQUIRED FOR PEON
      - ./status:/home/peon/status
      - ./upload:/home/peon/upload
      - ./download:/home/steam/.config/unity3d/IronGate/Valheim/worlds