#!/bin/bash
rootpath="/home/steam/server_files"
cd $rootpath
echo "###### Valhiem Server [STARTING]"
./valheim_server.x86_64 -name $SERVERNAME -port $PORT -world $WORLDNAME -password $PASSWORD -public 1