version: '3'
services:
  server:
    container_name: peon.warcamp.csgo.${SERVERNAME}
    hostname: peon.steamcmd.csgo
    image: umlatt/steamcmd
    ports:
      - ${PORT_GAME}:${PORT_GAME}/tcp
      - ${PORT_GAME}:${PORT_GAME}/udp
      - ${PORT_RCON}:${PORT_RCON}/tcp
      - ${PORT_RCON}:${PORT_RCON}/udp
    environment:
      - STEAMID=740
      - STEAM_GSLT=${STEAM_GSLT}
      - CSGO_GAME_TYPE=${CSGO_GAME_TYPE}
      - CSGO_GAME_MODE=${CSGO_GAME_MODE}
      - CSGO_MAP_GROUP=${CSGO_MAP_GROUP}
      - CSGO_MAP=${CSGO_MAP}
    volumes:
      - ./data:/home/steam/data
      - ./server_start:/init/server_start
      # ONLY REQUIRED FOR PEON
      - ./status:/home/peon/status
      - ./upload:/home/peon/upload