version: '3'
services:
  server:
    hostname: peon.steamcmd.csgo
    image: umlatt/steamcmd
    ports:
      - ${PORT_GAME}:${PORT_GAME}/tcp
      - ${PORT_GAME}:${PORT_GAME}/udp
      - ${PORT_RCON}:${PORT_RCON}/tcp
      - ${PORT_RCON}:${PORT_RCON}/udp
    environment:
      - STEAMID=740
      - STEAM_GSLT=${STEAM_GSLT}
    volumes:
      - ./server_files:/home/steam/server_files
      - ./server_start:/init/server_start
      # ONLY REQUIRED FOR PEON
      - ./status:/home/peon/status