#!/bin/bash
rootpath="/home/steam/server_files"
cd $rootpath
echo "###### CS:GO Server [STARTING]"
./srcds_run -game csgo -console -usercon +game_type 0 +game_mode 0 +mapgroup mg_active +map de_dust2 +sv_setsteamaccount $STEAM_GSLT
