version: '3'
services:
  server:
    container_name: peon.warcamp.valhiem.${SERVERNAME}
    hostname: peon.steamcmd.valhiem
    image: umlatt/steamcmd
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - STEAMID=896660
      # GAME SERVER VARIABLES
      - PORT=${PORT}
      - SERVERNAME=${SERVERNAME}
      - WORLDNAME=${WORLDNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./data:/home/steam/steamcmd/data
      - ./config:/home/steam/config
      - ./init_custom:/init/init_custom
      - ./server_start:/init/server_start
      - ./user:/home/steam/.config/unity3d/IronGate/Valheim