version: '3'
services:
  server:
    container_name: peon.warcamp.valhiem.${SERVERNAME}
    hostname: peon.steamcmd.valhiem
    image: umlatt/steamcmd
    ports:
      - 2456:2456
      - 2457:2457
    environment:
      - STEAMID=896660
      - PORT=${PORT}
      - SERVER_IP=${SERVER_IP}
      - SERVERNAME=${SERVERNAME}
      - WORLDNAME=${WORLDNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./data:/home/steam/data
      - ./server_start:/init/server_start
      - ./init_custom:/init/init_custom
      # ONLY REQUIRED FOR PEON
      - ./status:/home/peon/status
      - ./upload:/home/peon/upload
      - ./download:/home/peon/download