#!/bin/bash
echo "###### Valhiem Server [STARTING]"
cd /home/steam/data
./valheim_server.x86_64 -name $SERVERNAME -port $PORT -world $WORLDNAME -password $PASSWORD -savedir "/home/peon/download" -public 1