#!/bin/bash
echo "###### Valhiem Server $SERVERNAME [STARTING]"
cd /home/steam/data
./start_server.sh -name $SERVERNAME -port $PORT -world $WORLDNAME -password $PASSWORD -savedir "/home/peon/download" -public 1