#!/bin/bash
config_file="/home/steam/steamcmd/data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"
check_config_file(){
    if [ ! -f "$config_file" ]; then
        echo -n "BUILDING CONFIG FILES" > $STATE_FILE
        ./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS &
        PID=$!
        while [ ! -f "$config_file" ]; do
            sleep 1
        done
        sleep 10
        kill $PID
    fi
}

update_server_settings(){
    # General server settings
    [[ -n $SERVER_NAME ]] && echo "ServerName='$SERVER_NAME'" > $config_file
    [[ -n $SERVERDESCRIPTION ]] && echo "ServerDescription='$SERVERDESCRIPTION'" >> $config_file
    [[ -n $PASSWORD ]] && echo "ServerPassword='$PASSWORD'" >> $config_file
    [[ -n $ADMINPASSWORD ]] && echo "AdminPassword='$ADMINPASSWORD'" >> $config_file
    [[ -n $SERVERPLAYERMAXNUM ]] && echo "ServerPlayerMaxNum=$SERVERPLAYERMAXNUM" >> $config_file
    [[ -n $COOPLAYERMAXNUM ]] && echo "CoopPlayerMaxNum=$COOPLAYERMAXNUM" >> $config_file

    # Game mechanics
    [[ -n $DIFFICULTY ]] && echo "Difficulty='$DIFFICULTY'" >> $config_file
    [[ -n $DAYTIMESPEEDRATE ]] && echo "DayTimeSpeedRate=$DAYTIMESPEEDRATE" >> $config_file
    [[ -n $NIGHTTIMESPEEDRATE ]] && echo "NightTimeSpeedRate=$NIGHTTIMESPEEDRATE" >> $config_file
    [[ -n $EXPRATE ]] && echo "ExpRate=$EXPRATE" >> $config_file
    [[ -n $PALCAPTURERATE ]] && echo "PalCaptureRate=$PALCAPTURERATE" >> $config_file
    [[ -n $PALSPAWNNUMRATE ]] && echo "PalSpawnNumRate=$PALSPAWNNUMRATE" >> $config_file
    [[ -n $PALDAMAGERATEATTACK ]] && echo "PalDamageRateAttack=$PALDAMAGERATEATTACK" >> $config_file
    [[ -n $PALDAMAGERATEDEFENSE ]] && echo "PalDamageRateDefense=$PALDAMAGERATEDEFENSE" >> $config_file
    [[ -n $PLAYERDAMAGERATEATTACK ]] && echo "PlayerDamageRateAttack=$PLAYERDAMAGERATEATTACK" >> $config_file
    [[ -n $PLAYERDAMAGERATEDEFENSE ]] && echo "PlayerDamageRateDefense=$PLAYERDAMAGERATEDEFENSE" >> $config_file
    [[ -n $PLAYERSTOMACHDECREACERATE ]] && echo "PlayerStomachDecreaceRate=$PLAYERSTOMACHDECREACERATE" >> $config_file
    [[ -n $PLAYERSTAMINADECREACERATE ]] && echo "PlayerStaminaDecreaceRate=$PLAYERSTAMINADECREACERATE" >> $config_file
    [[ -n $PLAYERAUTOHPREGENERATE ]] && echo "PlayerAutoHPRegeneRate=$PLAYERAUTOHPREGENERATE" >> $config_file
    [[ -n $PLAYERAUTOHPREGENERATEINSLEEP ]] && echo "PlayerAutoHpRegeneRateInSleep=$PLAYERAUTOHPREGENERATEINSLEEP" >> $config_file
    [[ -n $PALSTOMACHDECREACERATE ]] && echo "PalStomachDecreaceRate=$PALSTOMACHDECREACERATE" >> $config_file
    [[ -n $PALSTAMINADECREACERATE ]] && echo "PalStaminaDecreaceRate=$PALSTAMINADECREACERATE" >> $config_file
    [[ -n $PALAUTOHPREGENERATE ]] && echo "PalAutoHPRegeneRate=$PALAUTOHPREGENERATE" >> $config_file
    [[ -n $PALAUTOHPREGENERATEINSLEEP ]] && echo "PalAutoHpRegeneRateInSleep=$PALAUTOHPREGENERATEINSLEEP" >> $config_file
    [[ -n $BUILDOBJECTDAMAGERATE ]] && echo "BuildObjectDamageRate=$BUILDOBJECTDAMAGERATE" >> $config_file
    [[ -n $BUILDOBJECTDETERIORATIONDAMAGERATE ]] && echo "BuildObjectDeteriorationDamageRate=$BUILDOBJECTDETERIORATIONDAMAGERATE" >> $config_file
    [[ -n $COLLECTIONDROPRATE ]] && echo "CollectionDropRate=$COLLECTIONDROPRATE" >> $config_file
    [[ -n $COLLECTIONOBJECTHPRATE ]] && echo "CollectionObjectHpRate=$COLLECTIONOBJECTHPRATE" >> $config_file
    [[ -n $COLLECTIONOBJECTRESPAWNSPEEDRATE ]] && echo "CollectionObjectRespawnSpeedRate=$COLLECTIONOBJECTRESPAWNSPEEDRATE" >> $config_file
    [[ -n $ENEMYDROPITEMRATE ]] && echo "EnemyDropItemRate=$ENEMYDROPITEMRATE" >> $config_file
    [[ -n $DEATHPENALTY ]] && echo "DeathPenalty='$DEATHPENALTY'" >> $config_file
    [[ -n $BENABLEAIMASSISTPAD ]] && echo "bEnableAimAssistPad=$BENABLEAIMASSISTPAD" >> $config_file
    [[ -n $BENABLEAIMASSISTKEYBOARD ]] && echo "bEnableAimAssistKeyboard=$BENABLEAIMASSISTKEYBOARD" >> $config_file
    [[ -n $DROPITEMMAXNUM ]] && echo "DropItemMaxNum=$DROPITEMMAXNUM" >> $config_file
    [[ -n $BASECAMPMAXNUM ]] && echo "BaseCampMaxNum=$BASECAMPMAXNUM" >> $config_file
    [[ -n $BASECAMPWORKERMAXNUM ]] && echo "BaseCampWorkerMaxNum=$BASECAMPWORKERMAXNUM" >> $config_file
    [[ -n $DROPITEMALIVEMAXHOURS ]] && echo "DropItemAliveMaxHours=$DROPITEMALIVEMAXHOURS" >> $config_file
    [[ -n $BAUTORESETGUILDNOONLINEPLAYERS ]] && echo "bAutoResetGuildNoOnlinePlayers=$BAUTORESETGUILDNOONLINEPLAYERS" >> $config_file
    [[ -n $AUTORESETGUILDTIMENOONLINEPLAYERS ]] && echo "AutoResetGuildTimeNoOnlinePlayers=$AUTORESETGUILDTIMENOONLINEPLAYERS" >> $config_file
    [[ -n $GUILDPLAYERMAXNUM ]] && echo "GuildPlayerMaxNum=$GUILDPLAYERMAXNUM" >> $config_file
    [[ -n $PALEGGDEFAULTHATCHINGTIME ]] && echo "PalEggDefaultHatchingTime=$PALEGGDEFAULTHATCHINGTIME" >> $config_file
    [[ -n $WORKSPEEDRATE ]] && echo "WorkSpeedRate=$WORKSPEEDRATE" >> $config_file
}