#!/bin/bash
config_file="/home/steam/steamcmd/data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"
check_config_file(){
    if [ ! -f "$config_file" ]; then
        echo -n "BUILDING CONFIG FILES" > $STATE_FILE
        ./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS &
        PID=$!
        while [ ! -f "$config_file" ]; do
            sleep 1
        done
        sleep 10
        kill $PID
    fi
}

update_server_settings(){
    echo "[/Script/Pal.PalGameWorldSettings]" > $config_file
    config_string="OptionSettings=("
    # General server settings
    [[ -n $SERVER_NAME ]] && config_string+="ServerName='$SERVER_NAME'" || config_string+="ServerName='PEONPAL'"
    [[ -n $SERVERDESCRIPTION ]] && config_string+="ServerDescription='$SERVERDESCRIPTION'" || config_string+="ServerDescription='A PALWORLD server built be PEON.'"
    [[ -n $PASSWORD ]] && config_string+="ServerPassword='$PASSWORD'" || config_string+="ServerPassword='zugzug'"
    [[ -n $ADMINPASSWORD ]] && config_string+="AdminPassword='$ADMINPASSWORD'" || config_string+="AdminPassword='zu88zu88'"
    [[ -n $SERVERPLAYERMAXNUM ]] && config_string+="ServerPlayerMaxNum=$SERVERPLAYERMAXNUM" || config_string+="ServerPlayerMaxNum=32"
    [[ -n $COOPLAYERMAXNUM ]] && config_string+="CoopPlayerMaxNum=$COOPLAYERMAXNUM" || config_string+="CoopPlayerMaxNum=4"
    # Network settings
    [[ -n $PORT ]] && config_string+="PublicPort=$PORT" || config_string+="PublicPort=8211"
    [[ -n $SERVER_IP ]] && config_string+="PublicIP='$SERVER_IP'" || config_string+="PublicIP='localhost'"
    [[ -n $RCONENABLED ]] && config_string+="RCONEnabled=$RCONENABLED" || config_string+="RCONEnabled=False"
    [[ -n $RCONPORT ]] && config_string+="RCONPort=$RCONPORT" || config_string+="RCONPort=25575"
    # Region and authentication
    [[ -n $REGION ]] && config_string+="Region='$REGION'" || config_string+="Region=''"
    [[ -n $BUSEAUTH ]] && config_string+="bUseAuth=$BUSEAUTH" || config_string+="bUseAuth=True"
    [[ -n $BANLISTURL ]] && config_string+="BanListURL='$BANLISTURL'" || config_string+="BanListURL='https://api.palworldgame.com/api/banlist.txt'"
    # Game mechanics
    [[ -n $DIFFICULTY ]] && config_string+="Difficulty=$DIFFICULTY" || config_string+="Difficulty=None"
    [[ -n $DAYTIMESPEEDRATE ]] && config_string+="DayTimeSpeedRate=$DAYTIMESPEEDRATE" || config_string+="DayTimeSpeedRate=1.000000"
    [[ -n $NIGHTTIMESPEEDRATE ]] && config_string+="NightTimeSpeedRate=$NIGHTTIMESPEEDRATE" || config_string+="NightTimeSpeedRate=1.000000"
    [[ -n $EXPRATE ]] && config_string+="ExpRate=$EXPRATE" || config_string+="ExpRate=1.000000"
    [[ -n $PALCAPTURERATE ]] && config_string+="PalCaptureRate=$PALCAPTURERATE" || config_string+="PalCaptureRate=1.000000"
    [[ -n $PALSPAWNNUMRATE ]] && config_string+="PalSpawnNumRate=$PALSPAWNNUMRATE" || config_string+="PalSpawnNumRate=1.000000"
    [[ -n $PALDAMAGERATEATTACK ]] && config_string+="PalDamageRateAttack=$PALDAMAGERATEATTACK" || config_string+="PalDamageRateAttack=1.000000"
    [[ -n $PALDAMAGERATEDEFENSE ]] && config_string+="PalDamageRateDefense=$PALDAMAGERATEDEFENSE" || config_string+="PalDamageRateDefense=1.000000"
    [[ -n $PLAYERDAMAGERATEATTACK ]] && config_string+="PlayerDamageRateAttack=$PLAYERDAMAGERATEATTACK" || config_string+="PlayerDamageRateAttack=1.000000"
    [[ -n $PLAYERDAMAGERATEDEFENSE ]] && config_string+="PlayerDamageRateDefense=$PLAYERDAMAGERATEDEFENSE" || config_string+="PlayerDamageRateDefense=1.000000"
    [[ -n $PLAYERSTOMACHDECREACERATE ]] && config_string+="PlayerStomachDecreaceRate=$PLAYERSTOMACHDECREACERATE" || config_string+="PlayerStomachDecreaceRate=1.000000"
    [[ -n $PLAYERSTAMINADECREACERATE ]] && config_string+="PlayerStaminaDecreaceRate=$PLAYERSTAMINADECREACERATE" || config_string+="PlayerStaminaDecreaceRate=1.000000"
    [[ -n $PLAYERAUTOHPREGENERATE ]] && config_string+="PlayerAutoHPRegeneRate=$PLAYERAUTOHPREGENERATE" || config_string+="PlayerAutoHPRegeneRate=1.000000"
    [[ -n $PLAYERAUTOHPREGENERATEINSLEEP ]] && config_string+="PlayerAutoHpRegeneRateInSleep=$PLAYERAUTOHPREGENERATEINSLEEP" || config_string+="PlayerAutoHpRegeneRateInSleep=1.000000"
    [[ -n $PALSTOMACHDECREACERATE ]] && config_string+="PalStomachDecreaceRate=$PALSTOMACHDECREACERATE" || config_string+="PalStomachDecreaceRate=1.000000"
    [[ -n $PALSTAMINADECREACERATE ]] && config_string+="PalStaminaDecreaceRate=$PALSTAMINADECREACERATE" || config_string+="PalStaminaDecreaceRate=1.000000"
    [[ -n $PALAUTOHPREGENERATE ]] && config_string+="PalAutoHPRegeneRate=$PALAUTOHPREGENERATE" || config_string+="PalAutoHPRegeneRate=1.000000"
    [[ -n $PALAUTOHPREGENERATEINSLEEP ]] && config_string+="PalAutoHpRegeneRateInSleep=$PALAUTOHPREGENERATEINSLEEP" || config_string+="PalAutoHpRegeneRateInSleep=1.000000"
    [[ -n $BUILDOBJECTDAMAGERATE ]] && config_string+="BuildObjectDamageRate=$BUILDOBJECTDAMAGERATE" || config_string+="BuildObjectDamageRate=1.000000"
    [[ -n $BUILDOBJECTDETERIORATIONDAMAGERATE ]] && config_string+="BuildObjectDeteriorationDamageRate=$BUILDOBJECTDETERIORATIONDAMAGERATE" || config_string+="BuildObjectDeteriorationDamageRate=1.000000"
    [[ -n $COLLECTIONDROPRATE ]] && config_string+="CollectionDropRate=$COLLECTIONDROPRATE" || config_string+=config_string+="CollectionDropRate=1.000000"
    [[ -n $COLLECTIONOBJECTHPRATE ]] && config_string+="CollectionObjectHpRate=$COLLECTIONOBJECTHPRATE" || config_string+=config_string+="CollectionObjectHpRate=1.000000"
    [[ -n $COLLECTIONOBJECTRESPAWNSPEEDRATE ]] && config_string+="CollectionObjectRespawnSpeedRate=$COLLECTIONOBJECTRESPAWNSPEEDRATE" || config_string+=config_string+="CollectionObjectRespawnSpeedRate=1.000000"
    [[ -n $ENEMYDROPITEMRATE ]] && config_string+="EnemyDropItemRate=$ENEMYDROPITEMRATE" || config_string+=config_string+="EnemyDropItemRate=1.000000"
    [[ -n $DEATHPENALTY ]] && config_string+="DeathPenalty='$DEATHPENALTY'" || config_string+="DeathPenalty=All"
    [[ -n $BENABLEAIMASSISTPAD ]] && config_string+="bEnableAimAssistPad=$BENABLEAIMASSISTPAD" || config_string+="bEnableAimAssistPad=True"
    [[ -n $BENABLEAIMASSISTKEYBOARD ]] && config_string+="bEnableAimAssistKeyboard=$BENABLEAIMASSISTKEYBOARD" || config_string+="bEnableAimAssistKeyboard=False"
    [[ -n $DROPITEMMAXNUM ]] && config_string+="DropItemMaxNum=$DROPITEMMAXNUM" || config_string+="DropItemMaxNum=3000"
    [[ -n $BASECAMPMAXNUM ]] && config_string+="BaseCampMaxNum=$BASECAMPMAXNUM" || config_string+="BaseCampMaxNum=128"
    [[ -n $BASECAMPWORKERMAXNUM ]] && config_string+="BaseCampWorkerMaxNum=$BASECAMPWORKERMAXNUM" || config_string+="BaseCampWorkerMaxNum=15"
    [[ -n $DROPITEMALIVEMAXHOURS ]] && config_string+="DropItemAliveMaxHours=$DROPITEMALIVEMAXHOURS" || config_string+="DropItemAliveMaxHours=1.000000"
    [[ -n $BAUTORESETGUILDNOONLINEPLAYERS ]] && config_string+="bAutoResetGuildNoOnlinePlayers=$BAUTORESETGUILDNOONLINEPLAYERS" || config_string+="bAutoResetGuildNoOnlinePlayers=False"
    [[ -n $AUTORESETGUILDTIMENOONLINEPLAYERS ]] && config_string+="AutoResetGuildTimeNoOnlinePlayers=$AUTORESETGUILDTIMENOONLINEPLAYERS" || config_string+="AutoResetGuildTimeNoOnlinePlayers=72.000000"
    [[ -n $GUILDPLAYERMAXNUM ]] && config_string+="GuildPlayerMaxNum=$GUILDPLAYERMAXNUM" || config_string+="GuildPlayerMaxNum=20"
    [[ -n $PALEGGDEFAULTHATCHINGTIME ]] && config_string+="PalEggDefaultHatchingTime=$PALEGGDEFAULTHATCHINGTIME" || config_string+="PalEggDefaultHatchingTime=72.000000"
    [[ -n $WORKSPEEDRATE ]] && config_string+="WorkSpeedRate=$WORKSPEEDRATE" || config_string+="WorkSpeedRate=1.000000"
    [[ -n $BENABLEPLAYERTOPLAYERDAMAGE ]] && config_string+="bEnablePlayerToPlayerDamage=$BENABLEPLAYERTOPLAYERDAMAGE" || config_string+="bEnablePlayerToPlayerDamage=False"
    [[ -n $BENABLEFRIENDLYFIRE ]] && config_string+="bEnableFriendlyFire=$BENABLEFRIENDLYFIRE" || config_string+="bEnableFriendlyFire=False"
    [[ -n $BENABLEINVADERENEMY ]] && config_string+="bEnableInvaderEnemy=$BENABLEINVADERENEMY" || config_string+="bEnableInvaderEnemy=True"
    [[ -n $BACTIVEUNKO ]] && config_string+="bActiveUNKO=$BACTIVEUNKO" || config_string+="bActiveUNKO=False"
    [[ -n $DROPITEMMAXNUMUNKO ]] && config_string+="DropItemMaxNum_UNKO=$DROPITEMMAXNUMUNKO" || config_string+="DropItemMaxNum_UNKO=100"
    [[ -n $BISMULTIPLAY ]] && config_string+="bIsMultiplay=$BISMULTIPLAY" || config_string+="bIsMultiplay=False"
    [[ -n $BISPVP ]] && config_string+="bIsPvP=$BISPVP" || config_string+="bIsPvP=False"
    [[ -n $BCANPICKUPOTHERGUILDDEATHPENALTYDROP ]] && config_string+="bCanPickupOtherGuildDeathPenaltyDrop=$BCANPICKUPOTHERGUILDDEATHPENALTYDROP" || config_string+="bCanPickupOtherGuildDeathPenaltyDrop=False"
    [[ -n $BENABLENONLOGINPENALTY ]] && config_string+="bEnableNonLoginPenalty=$BENABLENONLOGINPENALTY" || config_string+="bEnableNonLoginPenalty=True"
    [[ -n $BENABLEFASTTRAVEL ]] && config_string+="bEnableFastTravel=$BENABLEFASTTRAVEL" || config_string+="bEnableFastTravel=True"
    [[ -n $BISSTARTLOCATIONSELECTBYMAP ]] && config_string+="bIsStartLocationSelectByMap=$BISSTARTLOCATIONSELECTBYMAP" || config_string+="bIsStartLocationSelectByMap=True"
    [[ -n $BEXISTPLAYERAFTERLOGOUT ]] && config_string+="bExistPlayerAfterLogout=$BEXISTPLAYERAFTERLOGOUT" || config_string+="bExistPlayerAfterLogout=False"
    [[ -n $BENABLEDEFENSEOTHERGUILDPLAYER ]] && config_string+="bEnableDefenseOtherGuildPlayer=$BENABLEDEFENSEOTHERGUILDPLAYER" || config_string+="bEnableDefenseOtherGuildPlayer=False"
    config_string+=")"
    echo $config_string >> $config_file
}