#!/bin/bash
source /actions/configure_settings

echo "###### Server Enshrouded.$SERVER_NAME [STARTING]"
##### Server Config
echo $PORT > /home/steam/config/port
echo $SERVER_NAME > /home/steam/config/server_name 
echo $PASSWORD > /home/steam/config/password
#echo "THIS SERVER IS KNOWN TO TAKE UP TO 15 MINUTES TO START." > /home/steam/config/notice
update_server_settings
# CUSTOM GAME SERVER COMMAND
cd $INSTALL_DIR

/home/steam/steamcmd/compatibilitytools.d/GE-Proton9-18/proton run enshrouded_server.exe