#!/bin/bash
echo "###### Server Ark.$SERVER_NAME [STARTING]"
cd $INSTALL_DIR
##### Server Config
echo $PORT > /home/steam/config/port
echo $RCON > /home/steam/config/rcon
echo $SERVER_NAME > /home/steam/config/server_name 
echo $WORLD_NAME > /home/steam/config/world_name
echo $PASSWORD > /home/steam/config/password

##### CONTENTS OF server_start.sh
export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970

# Tip: Make a local copy of this script to avoid it being overwritten by steam.
# NOTE: Minimum password length is 5 characters & Password cant be in the server name.
# NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall

./ShooterGameServer TheIsland?listen?SessionName=$SERVER_NAME?ServerPassword=$PASSWORD?ServerAdminPassword=$ADMIN_PASSWORD -server -log

export LD_LIBRARY_PATH=$templdpath