#!/bin/bash
echo "###### Server Palworld.$SERVER_NAME [STARTING]"
cd $INSTALL_DIR
##### Server Config
echo $PORT > /home/steam/config/port
echo $SERVER_NAME > /home/steam/config/server_name 
echo $PASSWORD > /home/steam/config/password

##### CONTENTS OF server_start.sh
export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=2394010

# Tip: Make a local copy of this script to avoid it being overwritten by steam.
# NOTE: Minimum password length is 5 characters & Password cant be in the server name.
# NOTE: You need to make sure the ports 2188 is being forwarded to your server through your local router & firewall.
if [ ! -f "/home/steam/steamcmd/data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" ]; then
    ./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS &
    PID=$!
    while [ ! -f "/home/steam/steamcmd/data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini" ]; do
        sleep 1
    done
    sleep 10
    kill $PID
fi
echo "ServerPassword='$PASSWORD'" > /home/steam/steamcmd/data/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
./PalServer.sh -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS 

export LD_LIBRARY_PATH=$templdpath